runtime: nodejs18
env: standard
instance_class: F2
service: qahva-backend-service
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
entrypoint: node dist/app.js
readiness_check:
  path: "/_ah/ready"
  check_interval_sec: 30
  timeout_sec: 10 
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300